### PR TITLE
Remove references to FPGA IP core drivers

### PR DESCRIPTION
**Pull request by kowalewskijan**
This PR removes unnecessary references to FPGA IP core drivers which are not intended for HAL.

### CODE REVIEW

**Review by galak — APPROVED** [review]

**Review by PiotrZierhoffer — APPROVED** [review]
Lgtm, cleaning up the code is good

**Comment by PiotrZierhoffer** [comment]
@galak if you want us to wait for Carles with this one, then I'll wait. If not, then I'll just merge it

**Comment by galak** [comment]
> @galak if you want us to wait for Carles with this one, then I'll wait. If not, then I'll just merge it

We'll the practice is to have a PR on the Zephyr side to test this before we merge.  So I'd ask we do that before.

**Comment by kowalewskijan** [comment]
I prepared a [DNM PR](https://github.com/zephyrproject-rtos/zephyr/pull/28821) in Zephyr which just swaps remote in the west manifest to point to `antmicro:remove-ip-cores-references` for `hal_quicklogic` module. This DNM PR should prove if everything is ok with these changes introduced in the HAL PR.

**Comment by galak** [comment]
> I prepared a [DNM PR](https://github.com/zephyrproject-rtos/zephyr/pull/28821) in Zephyr which just swaps remote in the west manifest to point to `antmicro:remove-ip-cores-references` for `hal_quicklogic` module. This DNM PR should prove if everything is ok with these changes introduced in the HAL PR.

See my comment on PR #28821 on how this should be done.

https://docs.zephyrproject.org/latest/guides/modules.html?highlight=modules#process

**Pull request merged**
