### PR TITLE
EOS S3 HAL release

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This is the initial release of the EOS S3 HAL from QuickLogic.

It will be used for Chandalar and QuickFeather boards in Zephyr.

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Can you split this into multiple commits.  One for the files coming from the HAL and another for the Zephyr integration files.

Also, can you update the commit message for the HAL files to look something like:
https://github.com/zephyrproject-rtos/hal_stm32/commit/aa8da9ae9d785227cf944280b9cd38649d6e7bb4

**Comment by PiotrZierhoffer** [comment]
As there was no upstream repo or other public source for the HAL, I didn't reference it in the commit message

**Comment by galak** [comment]
> As there was no upstream repo or other public source for the HAL, I didn't reference it in the commit message

where did the code come from?

**Comment by galak** [comment]
@nashif can you see about adding the code scaning github action for this repo.

**Comment by PiotrZierhoffer** [comment]
> where did the code come from?

It was provided to us by QuickLogic and we helped making it open source

**Comment by PiotrZierhoffer** [comment]
@galak @nashif are github actions something that I can help with?

**Comment by galak** [comment]
> @galak @nashif are github actions something that I can help with?

Sure, take a look at https://github.com/zephyrproject-rtos/hal_atmel/tree/master/.github

**Comment by kowalewskijan** [comment]
I added scancode action for this repo similar to the one from [hal_atmel](https://github.com/zephyrproject-rtos/hal_atmel/tree/master/.github)

**Comment by PiotrZierhoffer** [comment]
I assume this has to be enabled on GitHub, and as far as I understand we can't do it ourselves. Is that correct? @nashif @galak

**Comment by mgielda** [comment]
Hi @nashif @galak @carlescufi , for more context, this is blocking https://github.com/zephyrproject-rtos/zephyr/pull/23565 which targets the first fully open source FPGA board (with vendor supported tooling) now shipping in CrowdSupply: https://www.crowdsupply.com/quicklogic/quickfeather

We would appreciate any help here, since we'd like users of the board to get started with Zephyr rather than bare metal / other OS alternatives.

**Comment by carlescufi** [comment]
@PiotrZierhoffer could you please specify the origin of this code in the commit where you import it? Did it come from a git repo? which SHA? or a download? from where? 

See this format here:
https://docs.zephyrproject.org/latest/contribute/index.html#identifying-contribution-origin

**Comment by PiotrZierhoffer** [comment]
@carlescufi this might be difficult, as we got the sources directly from QuickLogic. It was not public before and we got permission from them to opensource it.

Will such a clause pointing to our repo on which we released originally be enough?

**Comment by carlescufi** [comment]
> @carlescufi this might be difficult, as we got the sources directly from QuickLogic. It was not public before and we got permission from them to opensource it.
> 
> Will such a clause pointing to our repo on which we released originally be enough?

@PiotrZierhoffer
I think we have no other choice, let's go with that then.
EDIT: I merged this directly, didn't think it was actually even worth the trouble.

**Comment by carlescufi** [comment]
@galak can you please revisit?

**Review by carlescufi — APPROVED** [review]
Approving. Although we cannot reference a vendor URL for the origin, ANT Micro commits to maintaining this module repo.

**Review by galak — APPROVED** [review]

**Pull request merged**
